services:
  backend:
    volumes:
      - ./backend:/app
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql

  frontend:
    build: ./frontend
    volumes:
      -
    ports:
      - "5173:5173"

  mysql:
    image: mysql:8
    env_file:
      ./.env
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./urbanbotany.sql:/docker-entrypoint-initdb.d/urbanbotany.sql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql_data:
