%%{init:{'theme':'base'}}%%
usecaseDiagram
  actor User
  rectangle "Urban Botany System" {
    (Register)
    (Login)
    (Logout)
    (Reset Password)
    (Manage Profile)
  }
  User --> (Register)
  User --> (Login)
  User --> (Logout)
  User --> (Reset Password)
  User --> (Manage Profile)
  (Manage Profile) ..> (Login) : requires
