%%{init:{'theme':'base'}}%%
usecaseDiagram
  actor User
  rectangle "Urban Botany System" {
    (Create Room)
    (View Room)
    (Edit Room)
    (Delete Room)
    (Place Plant In Room)
    (Decorate Room)
    (Arrange Scene)
  }
  User --> (Create Room)
  User --> (View Room)
  User --> (Edit Room)
  User --> (Delete Room)
  User --> (Place Plant In Room)
  User --> (Decorate Room)
  User --> (Arrange Scene)

  (Place Plant In Room) .> (View Plant) : references
